spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: doctordb
      username: admin
      password: admin

eureka: 
  client: 
    service-url: 
      default-zone: http://EUREKA-REGISTRY
