spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: doctordb
#       username: root
#       password: root

eureka: 
  client: 
    service-url: 
      default-zone: http://EUREKA-REGISTRY
