spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/doctordb
      host: localhost
      port: 27017
      database: doctordb
      username: root
      password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Fullstack-Project


eureka: 
  client: 
    service-url: 
      default-zone: http://EUREKA-REGISTRY
      
app:
  cors-url: http://localhost:4200/
